### ISSUE TITLE
Make manifestoo check not blocking or at least separated

### ISSUE THREAD

**Issue by simahawk** [OCA/oca-addons-repo-template#113]
The current manifestoo check it too strict IMO.

You might have a PR which has green tests but that leads to a red build because of this check.
It would be nice to split it a separated check.

A possible use case: you open a PR w/ something experimental on a module that has dev status Beta and you add a dependency on a brand new module as Alpha because you want to test it first in real life together w/ the beta one.

I hope I explained myself correctly :smile: 

We could split the check and make it blocker for PR merge but make the tests run.

**Comment by pedrobaeza** [comment]
I don't get the case. Is it that you forget to put "Alpha" on depending modules? But that's like any other linter: fix it and push it.

**Comment by simahawk** [comment]
mod_a -> Beta, existing since a while
mod_b -> Alpha (because is brand new and you want to keep is alpha until you know it's stable enough)

Create a PR where mod_a it's made dependent on mod_b -> tests fails -> should only block merge but should keep running tests.

**Comment by pedrobaeza** [comment]
Then that's a bug. You can do alpha modules depending on beta ones.

**Comment by pedrobaeza** [comment]
Ah, no, sorry, it's the contrary. beta depends on alpha. That's correct. You should make b Alpha. And no, it shouldn't be that way. You will get a false green, and when trying to merge, finding continuous errors on merging, and you will blame the CI and merge manually...

**Comment by simahawk** [comment]
Why should you blame the CI? You'll see why is red and fix it.

**Comment by pedrobaeza** [comment]
You can do the same on your PR when proposed, not on merge.

**Comment by sbidoul** [comment]
This is a dupe of #83 I think we must make the dev status and license check non blocking on branches < 15 otherwise everything will be red when we deploy GitHub actions and shutdown travis. These issues must be fixed I agree, but it is a new check we are deploying so we need to leave contributors time to fix it and not block everything at once.

We could also make the checks opt-in on branches < 14 and mandatory on >= 15. But I dont know how to do that with copier (i.e; make a question depend on the answer of another question). Maybe @yajo can help here.

**Comment by sbidoul** [comment]
I think I'll move the dev and license checks to separate jobs. Because it does not play well with INCLUDE/EXCLUDE.

**Comment by sbidoul** [comment]
@simahawk not we now have a copier question to disable license and dev status checks.
