### ISSUE TITLE
[RFC] Replace pre-commit with precommix or pre-commit-hooks.nix

### ISSUE THREAD

**Issue by yajo** [OCA/oca-addons-repo-template#175]
**Is your feature request related to a problem?**
Here at OCA we use [pre-commit](https://pre-commit.com) extensively to make it more comfortable to share the same style of programming. It also bundles a lot of tools that help the coding and reviewing process.

However, pre-commit itself is divided into 3 parts:

1. Install the hooks.
2. Find the hooks.
3. Run the hooks.

While it's perfect for running the hooks, and pretty OK for finding them, it's not perfect for installing them. How can that be, if we pin the hook tags? Because everything that's below the hook (python version, or node version, or stdlib version, OS version, etc.) is not pinned.

The obvious outcome of this problem is that every now and then, some hook dependency starts failing, and then the CI and dev experiencie starts melting across all OCA repos. It becomes a maintenance burden with ease. Here I've collected some examples (related but not exclusive to OCA):

1. https://github.com/OCA/oca-addons-repo-template/pull/41
2. https://github.com/OCA/oca-addons-repo-template/issues/133
3. https://github.com/OCA/oca-addons-repo-template/pull/143
4. https://github.com/OCA/mis-builder/pull/476#issuecomment-1313663536
5. https://github.com/OCA/oca-addons-repo-template/issues/174
6. https://github.com/OCA/oca-addons-repo-template/pull/182
7. https://github.com/OCA/l10n-spain/pull/2783#issuecomment-1408349114
8. https://github.com/OCA/oca-addons-repo-template/pull/183
9. https://github.com/OCA/oca-addons-repo-template/pull/184
10. https://github.com/sbidoul/manifestoo/pull/53#issuecomment-1415764949
11. https://github.com/acsone/click-odoo-contrib/pull/126#issuecomment-1411805318
12. https://github.com/OCA/oca-addons-repo-template/issues/80
13. https://github.com/Tecnativa/doodba-copier-template/pull/370
14. https://github.com/OCA/oca-addons-repo-template/pull/188
15. https://github.com/OCA/oca-addons-repo-template/issues/193
16. https://github.com/OCA/oca-addons-repo-template/pull/194
17. https://github.com/OCA/oca-addons-repo-template/pull/196
18. https://github.com/OCA/oca-addons-repo-template/pull/199
19. https://github.com/OCA/oca-addons-repo-template/issues/200
20. https://github.com/OCA/oca-addons-repo-template/pull/198#issuecomment-1645652163
21. https://github.com/OCA/oca-addons-repo-template/issues/119

**Describe the solution you'd like**
Here at @moduon I've developed a definitive solution for this problem. It's https://gitlab.com/moduon/precommix. The base idea is that you use pre-commit for running the hooks (where it's perfect), but you use [nix](https://nixos.org/) to install the hooks (where it's perfect too) and [direnv](https://direnv.net/) to make them available for both pre-commit and your terminal/IDE (where it's perfect too).

Since Nix is the world's most obsessively perfect packager ever invented, once you package something there, it will keep working forever. Guaranteed. And every app bundles every dependency in a granular manner. So we will never have this problem again.

The "bad" parts of this approach:
1. You need to set up nix.
2. You need to set up direnv.
3. None of these work natively on Windows. You need to use WSL there.

None of these is particularly hard, but it can be annoying to bundle yet another tool in your belt for some people.

**Describe alternatives you've considered**
We could also bundle all current hooks in a docker image and use [the docker_image language](https://pre-commit.com/#docker_image) for pre-commit.

That would make you have to set up docker or podman instead of nix + direnv. This is more familiar for some people, although you lose some extra benefits of those tools.

FWIW, [we also provides docker images for precommix](https://gitlab.com/moduon/precommix/container_registry/3285154). Although the hooks are not currently tailored for using them (that shouldn't be too hard to add).

**Additional context**
I've used it for months. It's a total pleasure.

**Comment by sbidoul** [comment]
I'll try to find some time to try out pre-commitx and form myself an opinion - at first sight it may look like a bit of a steeper learning curve than `pipx install pre-commit` for the OCA contributors.

**Comment by carmenbianca** [comment]
I like the idea a lot, and I'm very charmed by Nix, but I don't think this is presently a workable solution due to the aforementioned learning curve. I wish Nix were easier than it is.

Just learning enough Nix to get the linters to run wouldn't be exactly sufficient, either. Inevitably, the user will want to reproduce some error that appears in the linter but not in their own Python virtualenv, and they'll need enough know-how of Nix to navigate that.

**Comment by yajo** [comment]
Well, you don't really need to know nix to use precommix. Just follow some instructions to setup your dev env. The magic is actually done by direnv. You can even use pre-commit installed with pipx or apt if you prefer, and they'll be compatible.

OTOH if you find it easier, we can use the same backend, but with `docker_image`. Users will just need to have installed podman or docker and hooks will keep working forever, which is the end goal. Yes, it's also another dependency. At least, more widespread.

**Comment by yajo** [comment]
Updating the list of issues in the description is becoming kinda fun... I have 14 already! 😸

**Comment by len-foss** [comment]
@yajo 
Well, outside of the 14 issue you listed, I can tell that I never created one but I think 10 hours wasted on pre-commit breaking is a rather low estimation (most of it when I was at Acsone).

Way too often you have a project that is mostly dormant, and when you come back a few months later some dependency is broken, and you have to find the right chain of dependency to get to a working solution again. And you have to be careful that after the version change it's using the exact same setting and doesn't start polluting all new commits by rewriting unrelated stuff in the file.

These dependencies, as you have noticed, might break in one setup but not in another (I saw how frequent it is as I changed from Ubuntu to Arch repos about one year ago). 
Which means in some case you might want to have a local version of the pre-commit to be able to work, diverging from the project one. This difference meant in some case Gitlab's pre-commit would rewrite something differently, so it required to manually making the change before pushing again (again, happened a few times at Acsone).

With regards to the solution, I think it's a great idea, a great choice of tools and a very sane approach.
I tested it, install was really simple since both nix and direnv are packaged, the whole setup took less than 10 minutes.
So I really hope this can go forward!

@sbidoul you should definitely give it a try!
