### ISSUE TITLE
pre-commit configuration too restrictive

### ISSUE THREAD

**Issue by amon-ra** [OCA/oca-addons-repo-template#4]
When working with 13.0 repos the pre-commit config makes commit fails in simple tasks. Example
```
reporting-engine/kpi_dashboard/static/src/js/widget/graph_widget.js
  19:13  error  'nv' is not defined                 no-undef
  23:35  error  'nv' is not defined                 no-undef
  23:47  error  'nv' is not defined                 no-undef
  27:17  error  'nv' is not defined                 no-undef
  31:36  error  'values' is defined but never used  no-unused-vars
  55:41  error  'd3' is not defined                 no-undef
  61:28  error  'd3' is not defined                 no-undef
  68:26  error  'nv' is not defined                 no-undef
  71:13  error  'd3' is not defined                 no-undef
  85:13  error  'nv' is not defined                 no-undef
```
This js file imports a library before using the variables, I think no-undef must be set to warn instead of fail. 
Where bot is pulling eslint config?
Thanks

**Comment by Yajo** [comment]
> This js file imports a library

Make sure the lib is inside `$module/static/lib`, which is ignored by pre-commit.

Otherwise, what you're displaying here are probably real problems. Say thanks to pre-commit :blush: 

If it's a really needed case where you need to have the code that way, you might also add some eslint comment tags to silent those lints.
