### ISSUE TITLE
[Question] Is .flake8 line length used?

### ISSUE THREAD

**Issue by LoisRForgeFlow** [OCA/oca-addons-repo-template#52]
The black configuration makes it adjust to a line legth of 88, but looking at the [configyuration of flake8](https://github.com/OCA/oca-addons-repo-template/blob/master/.flake8#L2) I see an 80.

This is at least misleading if it is not really used. Can this be removed or clarified?

**Comment by LoisRForgeFlow** [comment]
This is related to the pre-commit error seen in this manufacture pull request:

https://github.com/OCA/manufacture/pull/613/checks?check_run_id=2129342164#step:4:82

```
flake8 except __init__.py................................................Failed
- hook id: flake8
- exit code: 1

repair_stock_move/tests/test_repair_stock_move.py:73:92: B950 line too long (91 > 80 characters)
repair_stock_move/tests/test_repair_stock_move.py:75:92: B950 line too long (91 > 80 characters)
repair_stock_move/tests/test_repair_stock_move.py:91:90: B950 line too long (89 > 80 characters)
```

**Comment by Yajo** [comment]
It's used, but by flake8-bugbear, which allows a 10% margin, effectively warning when a line passes 88 characters. See https://github.com/PyCQA/flake8-bugbear#opinionated-warnings under the description for `B950`.

Based on this, black defaults to 88 max char length, and we're using that default. However, black is less strict and, if something is too uncomfortable to autoreformat, it just keeps the longer line untouched. This is the case for [the code you reference](https://github.com/OCA/manufacture/pull/613/files#diff-04150bb91da9b0dc68f6dd972d5660e5bd33e7a0ae8a55b1de3da0fe31c42639R73-R91):

![imagen](https://user-images.githubusercontent.com/973709/111468976-140b8500-871e-11eb-912e-6e48277f51d6.png)

According to current rules, your problem could only be worked around by:

1. Appending `  # noqa: B950` to those lines, actually making them even longer 😆 
2. Using variables instead of those long methods. But variables names must be short, and that sometimes doesn't help either.

So, leaving things as they are right now is indeed a source of problems. IMHO the correct setting would be one of:

1. Disabling it, as black will handle anything worth it, while still we'll be able to i.e. paste long URLs without worrying about linters, or make legitimate usages like the one affecting you right now.
2. Setting flake8 to max on 88, making `B950` fail only on 97 (88+10%), effectively applying the `B950` logic to our new reality.

What do you think @sbidoul?

**Comment by pedrobaeza** [comment]
For me it's ok as it is. Expanding the limit is only transferring the same debate to another range. Finding a good combination of intermediate variables and keeping code simple is a goal per se and expanding these limits makes the code less readable.

**Comment by LoisRForgeFlow** [comment]
@Yajo Thanks for the insights. I will now work around by using variables as you suggest. I will also follow the discussion here, it seems to me that indeed, we need a fix to make it more robust or to make flake8 and black get along better.

**Comment by sbidoul** [comment]
IIRC the current flake8 is the one that was recommended by black back then. Interestingly they now have [this](https://github.com/psf/black/tree/master/docs/compatible_configs).

That said I think stability in the linter configs is important, now. So if there is no strong reason to change I'd keep the status quo.

**Comment by Yajo** [comment]
I'll try to explain why we're using tools badly, and why these conflicts happen. Although we do have workarounds, that doesn't mean this isn't a problem, or that it can't be fixed. This isn't a corner case; I've found it myself several times, but since I happen to have the knowledge, I managed to workaround it. Besides, fixing this problem will give less headaches, not more, so it's not like we're going to interrupt anybody's work or produce a flood of ❌ along OCA repos.

First of all, just to make sure, please read carefully [the description of B950 here](https://github.com/PyCQA/flake8-bugbear/tree/e82bb8d8b855adbf1f6f9757fb1527e93039e0d9#opinionated-warnings). It's not long. I guess you already did, but I just want to make sure. Done? OK, let's continue.


See, right now we disable E501, which would error on a _strict_ 80 char limit:
https://github.com/OCA/oca-addons-repo-template/blob/aaff28dee7ef03da74f98f44f2df81ab77e06fe8/.flake8#L2
https://github.com/OCA/oca-addons-repo-template/blob/aaff28dee7ef03da74f98f44f2df81ab77e06fe8/.flake8#L8-L10

Line 8 says "covered by bugbear B950", but actually both checks are there for different purposes:

- E501: Absolutely forbidden to overpass 80 characters.
- B950: You shouldn't overpass 80 characters. But, for rare cases, you have a 10% extra margin. 😉 👉🏼 

If we were just humans (🤖) that difference wouldn't mean much, because humans usually just ignore warnings, so E501 at 88 or B950 at 80 would be mostly the same.

However, we are humans that use formatters, which make their own decisions on how to format code. Particularly, [black, has its own stand on this](https://github.com/psf/black/blob/692c0f50d91e3163bb87401e4a0e070b2eb5b163/docs/the_black_code_style.md#line-length). Quoting:

> Black will try to respect that. However, sometimes it won't be able to without breaking other rules. In those rare cases, auto-formatted code will exceed your allotted limit.

So, as you can see, black works out of the box with the same mindset as B950, and not E501.

If a line happens to measure 90 characters instead of 88, most chances are that it was black's decision and not the developer's decision. So, since black took that decision on its own, it makes no sense incomodating the developer (who didn't write code that way, to begin) with these little details.

Thus, the proper way to configure flake8 is with 88 limit and B950. It's not hard to do and it's not gonna cause any inconveniences, but the best of all is that it's gonna avoid these kind of confusions, which produce frustrations.

At the end of the day, our main goal introducing formatters was to simplify the life of devs and maintainers. The fact that a line measures 88 or 90 characters is not so important, when compared with the fact that a OCA contributions are easier and comfortable, and that one should be our priority here IMHO.

**Comment by pedrobaeza** [comment]
For me I would say is still moving the problem to other limit. I remember that black won't split this:
```python
temp_string = "Super long string that overpasses a lot the limit put, no matter if 80, 88 or 100 characters long"
```
so augmenting a bit the limit we only make a bit less readable the rest of the code.

**Comment by Yajo** [comment]
That case is one where the problem was produced by a human decision. Also, black has no way of beautifying it without altering the AST. Those kind of problems are OK.

However, look at this code:

```py
from odoo import _, api, fields, models


class ModelTechnicalName(models.Model):
    _name = "model.technical.name"
    _description = "Model Technical Name"

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if vals.get("some_field_you_wanna_check"):
                vals.update(
                    {
                        "contract_specific_product_ids": [
                            (
                                0,
                                0,
                                {
                                    "product_id":
                                        self._get_product_id_for_contract_specific()
                                },
                            )
                        ]
                    }
                )
        return super().create(vals_list)
```

As a human, I write this and it's perfectly compliant with all our formatters and linters. Line 20 has 84 chars long, so it fits inside those 88 I have. All is OK. However, black does:

```diff
@@ -16,8 +16,7 @@ class ModelTechnicalName(models.Model):
                                 0,
                                 0,
                                 {
-                                    "product_id":
-                                        self._get_product_id_for_contract_specific()
+                                    "product_id": self._get_product_id_for_contract_specific()
                                 },
                             )
                         ]
```

In this moment, I produced one of those cases where black ignores the limit hint because it decides the code looks better like this, even when it overpasses its line limit hint. This was a automated decision, so its fix should be automated too where possible.

These are the kind of cases we'd be avoiding.

If we have a tool that formats code, we need to make sure that the tool that checks it is configured likewise. Otherwise, both will collide at some point and interrupt our dear contributors' workflow.

If we try more, we could get to a case that also wouldn't be covered by this solution. However, even in that case, we'd still be better than before, because the error would have more chances of being meaningful. Besides, this particular case I'm demonstrating here happens often and is annoying. Other more rare cases can be treated later if/when they happen.

**Comment by pedrobaeza** [comment]
I still think that's only moving the problem to another limit. If you method name is:
```python
"product_id": self._get_product_id_for_contract_specific_with_a_very_long_name_that_is_more_than_any_other_method_name()
```
Are you going to allow that? You should set a sane limit for avoiding abuses, so better to set it as a lower one. The cyclomatic complexity also enters in this game, as having lots of indentation levels means that your code has a lot of flow paths that doesn't make it very convenient.

In your example, it's reasonable to refactor that to:
```python

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if not vals.get("some_field_you_wanna_check"):
                continue
            vals.update(
                ...
```

**Comment by Yajo** [comment]
I'm not sure you're understanding the problem.

It's not like the code I posted was perfect, or that its complexity couldn't be reduced. The point is that _the dev didn't introduce the problem_, so we can consider the dev's job was "good". Yes, it could be better, but it wasn't "bad". What turned that into "bad" was the tool, not the dev.

FWIW black maintainers have merged https://github.com/psf/black/pull/2050 to fix their docs. Black's new official recommendation is the same I'm telling here. I think that settles the point, so I'll open the PR.

**Comment by pedrobaeza** [comment]
OK, we can change to 88, and we'll have this conversation again later I suppose when with that limits, another similar condition will raise. But this should be done for upcoming v15 pre-config configuration.
