### ISSUE TITLE
[RFC] GitHub actions: make the dev status check optional

### ISSUE THREAD

**Issue by sbidoul** [OCA/oca-addons-repo-template#83]
If we deploy GitHub actions on 14 or 13, we should make the development status check non blocking (see for instance https://github.com/OCA/l10n-italy/pull/2468).

This can be done with a copier question.

**Comment by BT-rmartin** [comment]
I would also vote for doing the check on its own job and marking it as optional. Otherwise for old modules, it requires the action on several modules involving their authors/maintainers, as one module could become Stable but the dependencies stay as beta, and right now the check is blocking, when it's something not such critical imho. 
Example: https://github.com/OCA/delivery-carrier/runs/6116809311?check_suite_focus=true

**Comment by pedrobaeza** [comment]
The problem is not that one, as the PR is resolving it. It shouldn't be ignored, as the main goal of development_status will be obfuscated.

**Comment by sbidoul** [comment]
I also think we must make the transition to GitHub actions as friction-less as possible.

So I suggest having a copier question to enable/disable the license and dev status check (so PSCs can choose), and make it mandatory for v15+.

**Comment by sbidoul** [comment]
This was implemented in https://github.com/OCA/oca-addons-repo-template/pull/144
